#if !canImport(ObjectiveC)
  import XCTest

  extension PrchVaporTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PrchVaporTests = [
      ("testPrchVapor", testPrchVapor)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(PrchVaporTests.__allTests__PrchVaporTests)
    ]
  }
#endif
